//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh__Config__PTofCls__LMCPublisher 
  {
    CHMETH *pMeth;
    _Config_ dData;
    SVRDSC *pDsc;
  } SvrCh__Config__PTofCls__LMCPublisher;

typedef struct CltCh__Config__PTofCls__LMCPublisher 
  {
    struct SvrCh__Config__PTofCls__LMCPublisher *pCh;
    _Config_ dData;
    SVRCHCMD *pCmd;
  } CltCh__Config__PTofCls__LMCPublisher;

typedef struct SvrCh__SDDISTATE 
  {
    CHMETH *pMeth;
    _SDDISTATE dData;
    SVRDSC *pDsc;
  } SvrCh__SDDISTATE;

typedef struct CltCh__SDDISTATE 
  {
    struct SvrCh__SDDISTATE *pCh;
    _SDDISTATE dData;
    SVRCHCMD *pCmd;
  } CltCh__SDDISTATE;

typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct CltCh_BDINT 
  {
    struct SvrCh_BDINT *pCh;
    BDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_BDINT;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_RunningStateEnum 
  {
    CHMETH *pMeth;
    RunningStateEnum dData;
    SVRDSC *pDsc;
  } SvrCh_RunningStateEnum;

typedef struct CltCh_RunningStateEnum 
  {
    struct SvrCh_RunningStateEnum *pCh;
    RunningStateEnum dData;
    SVRCHCMD *pCmd;
  } CltCh_RunningStateEnum;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__16Alarms 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _16Alarms *pCmd;
  } CltChCmd__16Alarms;

typedef struct CltChCmd__AlarmX0Para 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _AlarmX0Para *pCmd;
  } CltChCmd__AlarmX0Para;

typedef struct CltChCmd__AlarmX1Para 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _AlarmX1Para *pCmd;
  } CltChCmd__AlarmX1Para;

typedef struct SvrChCmd__LMCAXIS_OPMODE 
  {
    CMDMETH *pMeth;
    _LMCAXIS_OPMODE dData;
    SVRDSC *pDsc;
  } SvrChCmd__LMCAXIS_OPMODE;

typedef struct CltChCmd__AxisBase 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _AxisBase *pCmd;
  } CltChCmd__AxisBase;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct CltChCmd__Bit32 
  {
    struct SvrChCmd_BDINT *pCh;
    BDINT dData;
    _Bit32 *pCmd;
  } CltChCmd__Bit32;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__CheckSum 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CheckSum *pCmd;
  } CltChCmd__CheckSum;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Grafix 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Grafix *pCmd;
  } CltChCmd__Grafix;

typedef struct CltChCmd__IP 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _IP *pCmd;
  } CltChCmd__IP;

typedef struct CltChCmd__Linker 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Linker *pCmd;
  } CltChCmd__Linker;

typedef struct CltChCmd__LMCABSEncoder 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCABSEncoder *pCmd;
  } CltChCmd__LMCABSEncoder;

typedef struct CltChCmd__LMCAxis 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxis *pCmd;
  } CltChCmd__LMCAxis;

typedef struct CltChCmd__LMCAxisBase 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxisBase *pCmd;
  } CltChCmd__LMCAxisBase;

typedef struct CltChCmd__LMCAxisRef 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisRef *pCmd;
  } CltChCmd__LMCAxisRef;

typedef struct CltChCmd__LMCAxisVis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVis *pCmd;
  } CltChCmd__LMCAxisVis;

typedef struct CltChCmd__LMCAxisVisInt 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisInt *pCmd;
  } CltChCmd__LMCAxisVisInt;

typedef struct CltChCmd__LMCAxisVisLogHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogHandle *pCmd;
  } CltChCmd__LMCAxisVisLogHandle;

typedef struct CltChCmd__LMCAxisVisLogViewer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogViewer *pCmd;
  } CltChCmd__LMCAxisVisLogViewer;

typedef struct CltChCmd__LMCAxisVisPara 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisPara *pCmd;
  } CltChCmd__LMCAxisVisPara;

typedef struct CltChCmd__LMCBaseCoord 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCBaseCoord *pCmd;
  } CltChCmd__LMCBaseCoord;

typedef struct SvrChCmd_ProfileCommandStatus 
  {
    CMDMETH *pMeth;
    ProfileCommandStatus dData;
    SVRDSC *pDsc;
  } SvrChCmd_ProfileCommandStatus;

typedef struct CltChCmd__LMCCalcModelBase 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    _LMCCalcModelBase *pCmd;
  } CltChCmd__LMCCalcModelBase;

typedef struct CltChCmd__LMCCalcModelController 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCCalcModelController *pCmd;
  } CltChCmd__LMCCalcModelController;

typedef struct CltChCmd__LMCMath_SO3 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCMath_SO3 *pCmd;
  } CltChCmd__LMCMath_SO3;

typedef struct CltChCmd__LMCMathFunctions 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCMathFunctions *pCmd;
  } CltChCmd__LMCMathFunctions;

typedef struct CltChCmd__LMCProfileBase 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    _LMCProfileBase *pCmd;
  } CltChCmd__LMCProfileBase;

typedef struct CltChCmd__LMCProfileBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileBuffer *pCmd;
  } CltChCmd__LMCProfileBuffer;

typedef struct CltChCmd__LMCProfileLog 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileLog *pCmd;
  } CltChCmd__LMCProfileLog;

typedef struct CltChCmd__LMCProfileVis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVis *pCmd;
  } CltChCmd__LMCProfileVis;

typedef struct CltChCmd__LMCProfileVisAxis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisAxis *pCmd;
  } CltChCmd__LMCProfileVisAxis;

typedef struct CltChCmd__LMCProfileVisInt 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisInt *pCmd;
  } CltChCmd__LMCProfileVisInt;

typedef struct CltChCmd__LMCProfileVisMovePara 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisMovePara *pCmd;
  } CltChCmd__LMCProfileVisMovePara;

typedef struct CltChCmd__LMCPublisher 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCPublisher *pCmd;
  } CltChCmd__LMCPublisher;

typedef struct CltChCmd__LMCRefBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCRefBase *pCmd;
  } CltChCmd__LMCRefBase;

typedef struct CltChCmd__LMCRobotLog 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCRobotLog *pCmd;
  } CltChCmd__LMCRobotLog;

typedef struct CltChCmd__LMCSafety 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCSafety *pCmd;
  } CltChCmd__LMCSafety;

typedef struct CltChCmd__LMCTool 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCTool *pCmd;
  } CltChCmd__LMCTool;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__OsziLSEBackground 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OsziLSEBackground *pCmd;
  } CltChCmd__OsziLSEBackground;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct CltChCmd__SysMsg 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SysMsg *pCmd;
  } CltChCmd__SysMsg;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct CltChCmd_AccessControlMain 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    AccessControlMain *pCmd;
  } CltChCmd_AccessControlMain;

typedef struct CltChCmd_AlarmDisplayList2 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    AlarmDisplayList2 *pCmd;
  } CltChCmd_AlarmDisplayList2;

typedef struct CltChCmd_AlarmTitleLine 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    AlarmTitleLine *pCmd;
  } CltChCmd_AlarmTitleLine;

typedef struct CltChCmd_ASCII_BIN 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ASCII_BIN *pCmd;
  } CltChCmd_ASCII_BIN;

typedef struct CltChCmd_Comm_SendData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Comm_SendData *pCmd;
  } CltChCmd_Comm_SendData;

typedef struct CltChCmd_Controller 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Controller *pCmd;
  } CltChCmd_Controller;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_CriticalSection 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    CriticalSection *pCmd;
  } CltChCmd_CriticalSection;

typedef struct CltChCmd_DataManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DataManager *pCmd;
  } CltChCmd_DataManager;

typedef struct CltChCmd_DataManagerFIFO 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerFIFO *pCmd;
  } CltChCmd_DataManagerFIFO;

typedef struct CltChCmd_DataManagerPriority 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerPriority *pCmd;
  } CltChCmd_DataManagerPriority;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

typedef struct CltChCmd_DateAndTime 
  {
    struct SvrChCmd_DATE_LSL *pCh;
    DATE_LSL dData;
    DateAndTime *pCmd;
  } CltChCmd_DateAndTime;

typedef struct SvrChCmd_iprStates 
  {
    CMDMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrChCmd_iprStates;

typedef struct CltChCmd_Diagnostic 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    Diagnostic *pCmd;
  } CltChCmd_Diagnostic;

typedef struct CltChCmd_DiagnosticBase 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    DiagnosticBase *pCmd;
  } CltChCmd_DiagnosticBase;

typedef struct CltChCmd_DiagnosticStationFileFolderHandler 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    DiagnosticStationFileFolderHandler *pCmd;
  } CltChCmd_DiagnosticStationFileFolderHandler;

typedef struct CltChCmd_DiagnosticStationHandlerBase 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    DiagnosticStationHandlerBase *pCmd;
  } CltChCmd_DiagnosticStationHandlerBase;

typedef struct CltChCmd_DiagnosticUserFunction 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    DiagnosticUserFunction *pCmd;
  } CltChCmd_DiagnosticUserFunction;

typedef struct CltChCmd_DiagnosticUserFunction_PLC 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    DiagnosticUserFunction_PLC *pCmd;
  } CltChCmd_DiagnosticUserFunction_PLC;

typedef struct CltChCmd_DiagnosticWork 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    DiagnosticWork *pCmd;
  } CltChCmd_DiagnosticWork;

typedef struct CltChCmd_DiagnosticWork_PLC 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    DiagnosticWork_PLC *pCmd;
  } CltChCmd_DiagnosticWork_PLC;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_DisplaySettings 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DisplaySettings *pCmd;
  } CltChCmd_DisplaySettings;

typedef struct CltChCmd_EventJournal 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EventJournal *pCmd;
  } CltChCmd_EventJournal;

typedef struct CltChCmd_EventQueue 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EventQueue *pCmd;
  } CltChCmd_EventQueue;

typedef struct CltChCmd_FileTransfer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    FileTransfer *pCmd;
  } CltChCmd_FileTransfer;

typedef struct CltChCmd_FileTransfer_RecvData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    FileTransfer_RecvData *pCmd;
  } CltChCmd_FileTransfer_RecvData;

typedef struct SvrChCmd__FT_State_PTofCls_FileTransferHandle 
  {
    CMDMETH *pMeth;
    _FT_State dData;
    SVRDSC *pDsc;
  } SvrChCmd__FT_State_PTofCls_FileTransferHandle;

typedef struct CltChCmd_FileTransferHandle 
  {
    struct SvrChCmd__FT_State_PTofCls_FileTransferHandle *pCh;
    _FT_State dData;
    FileTransferHandle *pCmd;
  } CltChCmd_FileTransferHandle;

typedef struct CltChCmd_FolderTransfer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    FolderTransfer *pCmd;
  } CltChCmd_FolderTransfer;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_GetOSVer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetOSVer *pCmd;
  } CltChCmd_GetOSVer;

typedef struct CltChCmd_GetTaskHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetTaskHandle *pCmd;
  } CltChCmd_GetTaskHandle;

typedef struct CltChCmd_GiveConfigNumber 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GiveConfigNumber *pCmd;
  } CltChCmd_GiveConfigNumber;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct CltChCmd_KeyPadAnumFileExplorer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    KeyPadAnumFileExplorer *pCmd;
  } CltChCmd_KeyPadAnumFileExplorer;

typedef struct CltChCmd_KeyPadImages 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    KeyPadImages *pCmd;
  } CltChCmd_KeyPadImages;

typedef struct CltChCmd_KeyPadImagesStdTemplate 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    KeyPadImagesStdTemplate *pCmd;
  } CltChCmd_KeyPadImagesStdTemplate;

typedef struct CltChCmd_LasalBuiltDate 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    LasalBuiltDate *pCmd;
  } CltChCmd_LasalBuiltDate;

typedef struct CltChCmd_Logic_And_10 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Logic_And_10 *pCmd;
  } CltChCmd_Logic_And_10;

typedef struct CltChCmd_LseBuiltDate 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    LseBuiltDate *pCmd;
  } CltChCmd_LseBuiltDate;

typedef struct CltChCmd_Merker 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Merker *pCmd;
  } CltChCmd_Merker;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_NetworkConfig 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    NetworkConfig *pCmd;
  } CltChCmd_NetworkConfig;

typedef struct CltChCmd_ProfileCommandStatus 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    SVRCHCMD *pCmd;
  } CltChCmd_ProfileCommandStatus;

typedef struct CltChCmd_ProjectGlobal 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ProjectGlobal *pCmd;
  } CltChCmd_ProjectGlobal;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RAMex 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RAMex *pCmd;
  } CltChCmd_RAMex;

typedef struct CltChCmd_RamRingBuffer 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamRingBuffer *pCmd;
  } CltChCmd_RamRingBuffer;

typedef struct CltChCmd_ReceiveDataCMD 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ReceiveDataCMD *pCmd;
  } CltChCmd_ReceiveDataCMD;

typedef struct CltChCmd_ReceiveDataCMD_PLC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ReceiveDataCMD_PLC *pCmd;
  } CltChCmd_ReceiveDataCMD_PLC;

typedef struct CltChCmd_RecipeHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    RecipeHandle *pCmd;
  } CltChCmd_RecipeHandle;

typedef struct CltChCmd_RecipeName 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    RecipeName *pCmd;
  } CltChCmd_RecipeName;

typedef struct CltChCmd_SCL_GetClassVersion 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SCL_GetClassVersion *pCmd;
  } CltChCmd_SCL_GetClassVersion;

typedef struct CltChCmd_SendDataCMD 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SendDataCMD *pCmd;
  } CltChCmd_SendDataCMD;

typedef struct CltChCmd_SendDataCMD_PLC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SendDataCMD_PLC *pCmd;
  } CltChCmd_SendDataCMD_PLC;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_Standard 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Standard *pCmd;
  } CltChCmd_Standard;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringBaseGB 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    StringBaseGB *pCmd;
  } CltChCmd_StringBaseGB;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct CltChCmd_StringRAM 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringRAM *pCmd;
  } CltChCmd_StringRAM;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct CltChCmd_SystemLogging 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SystemLogging *pCmd;
  } CltChCmd_SystemLogging;

typedef struct CltChCmd_TCPCommunication 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunication *pCmd;
  } CltChCmd_TCPCommunication;

typedef struct CltChCmd_TCPCommunicationLogFilter 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunicationLogFilter *pCmd;
  } CltChCmd_TCPCommunicationLogFilter;

typedef struct CltChCmd_TCPComReceiveData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPComReceiveData *pCmd;
  } CltChCmd_TCPComReceiveData;

typedef struct CltChCmd_TCPComSendData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPComSendData *pCmd;
  } CltChCmd_TCPComSendData;

typedef struct CltChCmd_TerminalControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TerminalControl *pCmd;
  } CltChCmd_TerminalControl;

typedef struct CltChCmd_TitleLine 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TitleLine *pCmd;
  } CltChCmd_TitleLine;

typedef struct SvrCh__CommandList_PTofCls__LMCAxisBase 
  {
    CHMETH *pMeth;
    _CommandList dData;
    SVRDSC *pDsc;
  } SvrCh__CommandList_PTofCls__LMCAxisBase;

typedef struct SvrCh__DDE_DATIM 
  {
    CHMETH *pMeth;
    _DDE_DATIM dData;
    SVRDSC *pDsc;
  } SvrCh__DDE_DATIM;

typedef struct SvrCh__FT_State_PTofCls_FileTransferHandle 
  {
    CHMETH *pMeth;
    _FT_State dData;
    SVRDSC *pDsc;
  } SvrCh__FT_State_PTofCls_FileTransferHandle;

typedef struct SvrCh__FT_SubState_PTofCls_FileTransferHandle 
  {
    CHMETH *pMeth;
    _FT_SubState dData;
    SVRDSC *pDsc;
  } SvrCh__FT_SubState_PTofCls_FileTransferHandle;

typedef struct SvrCh__LMCAXIS_CMDERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_CMDERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_CMDERROR;

typedef struct SvrCh__LMCAXIS_ERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR;

typedef struct SvrCh__LMCAXIS_ERROR_CONFIG 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR_CONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR_CONFIG;

typedef struct SvrCh__LMCAXIS_MOVE_RELATIVE_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVE_RELATIVE_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVE_RELATIVE_MODE;

typedef struct SvrCh__LMCAXIS_MOVEDIRECTION 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEDIRECTION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEDIRECTION;

typedef struct SvrCh__LMCAXIS_MOVEPROFILE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEPROFILE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEPROFILE;

typedef struct SvrCh__LMCAXIS_OPMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_OPMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_OPMODE;

typedef struct SvrCh__LMCAXIS_POSMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POSMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POSMODE;

typedef struct SvrCh__LMCAXIS_POWER_OFF_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POWER_OFF_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POWER_OFF_MODE;

typedef struct SvrCh__LMCAXIS_REFMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_REFMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_REFMODE;

typedef struct SvrCh__LMCAXIS_SETPARAMETER 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPARAMETER dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPARAMETER;

typedef struct SvrCh__LMCAXIS_SETPOSITION 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPOSITION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPOSITION;

typedef struct SvrCh__LMCAXIS_SETSWENDPOS 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETSWENDPOS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETSWENDPOS;

typedef struct SvrCh__LMCAXIS_STATUS 
  {
    CHMETH *pMeth;
    _LMCAXIS_STATUS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_STATUS;

typedef struct SvrCh__LMCCONTROLLERTYPE 
  {
    CHMETH *pMeth;
    _LMCCONTROLLERTYPE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCCONTROLLERTYPE;

typedef struct SvrCh__LMCPROF_OPMODE 
  {
    CHMETH *pMeth;
    _LMCPROF_OPMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROF_OPMODE;

typedef struct SvrCh__LMCPROFCIRCLEDEF 
  {
    CHMETH *pMeth;
    _LMCPROFCIRCLEDEF dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCIRCLEDEF;

typedef struct SvrCh__LMCPROFCMDCONFIG 
  {
    CHMETH *pMeth;
    _LMCPROFCMDCONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCMDCONFIG;

typedef struct SvrCh__LMCPROFCMDTYPES 
  {
    CHMETH *pMeth;
    _LMCPROFCMDTYPES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCMDTYPES;

typedef struct SvrCh__LMCPROFERRORTYPES 
  {
    CHMETH *pMeth;
    _LMCPROFERRORTYPES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFERRORTYPES;

typedef struct SvrCh__LMCPROFERRWARNCONFIG 
  {
    CHMETH *pMeth;
    _LMCPROFERRWARNCONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFERRWARNCONFIG;

typedef struct SvrCh__LMCPROFILESTATES 
  {
    CHMETH *pMeth;
    _LMCPROFILESTATES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFILESTATES;

typedef struct SvrCh__LMCPROFMOVEPROFILE 
  {
    CHMETH *pMeth;
    _LMCPROFMOVEPROFILE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFMOVEPROFILE;

typedef struct SvrCh__LMCPROFPARAMETER 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETER dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETER;

typedef struct SvrCh__LMCPROFPARAMETERAXIS 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETERAXIS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETERAXIS;

typedef struct SvrCh__LMCPROFPARAMETERGROUPS 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETERGROUPS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETERGROUPS;

typedef struct SvrCh__LMCPROFTRANSMODES 
  {
    CHMETH *pMeth;
    _LMCPROFTRANSMODES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFTRANSMODES;

typedef struct SvrCh__POSFLAGS 
  {
    CHMETH *pMeth;
    _POSFLAGS dData;
    SVRDSC *pDsc;
  } SvrCh__POSFLAGS;

typedef struct SvrCh__ROBOT_MODE_PTofCls__LMCRobotBase 
  {
    CHMETH *pMeth;
    _ROBOT_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__ROBOT_MODE_PTofCls__LMCRobotBase;

typedef struct SvrCh__ROBOT_STATUS_PTofCls__LMCRobotBase 
  {
    CHMETH *pMeth;
    _ROBOT_STATUS dData;
    SVRDSC *pDsc;
  } SvrCh__ROBOT_STATUS_PTofCls__LMCRobotBase;

typedef struct SvrCh_DM_CPU_Types 
  {
    CHMETH *pMeth;
    DM_CPU_Types dData;
    SVRDSC *pDsc;
  } SvrCh_DM_CPU_Types;

typedef struct SvrCh_e_GetOptions_PTofCls_NetworkConfig 
  {
    CHMETH *pMeth;
    e_GetOptions dData;
    SVRDSC *pDsc;
  } SvrCh_e_GetOptions_PTofCls_NetworkConfig;

typedef struct SvrCh_e_SetOptions_PTofCls_NetworkConfig 
  {
    CHMETH *pMeth;
    e_SetOptions dData;
    SVRDSC *pDsc;
  } SvrCh_e_SetOptions_PTofCls_NetworkConfig;

typedef struct SvrCh_EventTypeTxt_PTofCls_SCBase 
  {
    CHMETH *pMeth;
    EventTypeTxt dData;
    SVRDSC *pDsc;
  } SvrCh_EventTypeTxt_PTofCls_SCBase;

typedef struct SvrCh_Exec_PTofCls__FileExplorer 
  {
    CHMETH *pMeth;
    Exec dData;
    SVRDSC *pDsc;
  } SvrCh_Exec_PTofCls__FileExplorer;

typedef struct SvrCh_FexSortCrit_PTofCls__FileExplorer 
  {
    CHMETH *pMeth;
    FexSortCrit dData;
    SVRDSC *pDsc;
  } SvrCh_FexSortCrit_PTofCls__FileExplorer;

typedef struct SvrCh_iprStates 
  {
    CHMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrCh_iprStates;

typedef struct SvrCh_OptiesEnum 
  {
    CHMETH *pMeth;
    OptiesEnum dData;
    SVRDSC *pDsc;
  } SvrCh_OptiesEnum;

typedef struct SvrCh_T_BITS_PTofCls_EventExport 
  {
    CHMETH *pMeth;
    T_BITS dData;
    SVRDSC *pDsc;
  } SvrCh_T_BITS_PTofCls_EventExport;

typedef struct SvrCh_T_BITS_PTofCls_EventJournal 
  {
    CHMETH *pMeth;
    T_BITS dData;
    SVRDSC *pDsc;
  } SvrCh_T_BITS_PTofCls_EventJournal;

typedef struct SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication 
  {
    CHMETH *pMeth;
    t_e_ConnectionType dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication;

typedef struct SvrCh_t_e_ExportState_PTofCls_TCPCommunicationLogViewer 
  {
    CHMETH *pMeth;
    t_e_ExportState dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_ExportState_PTofCls_TCPCommunicationLogViewer;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct SvrChCmd__FSM_TCP_USER 
  {
    CMDMETH *pMeth;
    _FSM_TCP_USER dData;
    SVRDSC *pDsc;
  } SvrChCmd__FSM_TCP_USER;

typedef struct SvrChCmd_HDINT 
  {
    CMDMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_HDINT;

typedef struct SvrChCmd_IO_State 
  {
    CMDMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrChCmd_IO_State;

typedef struct SvrChCmd_T_BITS_PTofCls_Bit32Mask 
  {
    CMDMETH *pMeth;
    T_BITS dData;
    SVRDSC *pDsc;
  } SvrChCmd_T_BITS_PTofCls_Bit32Mask;

