//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SvrCh__Config__PTofCls__LMCPublisher : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPublisher::_Config_;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh__Config__PTofCls__LMCPublisher : STRUCT
    pCh : ^SvrCh__Config__PTofCls__LMCPublisher;
    dData : _LMCPublisher::_Config_;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh__SDDISTATE : STRUCT
    pMeth : ^CHMETH;
    dData : _SDDISTATE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh__SDDISTATE : STRUCT
    pCh : ^SvrCh__SDDISTATE;
    dData : _SDDISTATE;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_BDINT : STRUCT
    pMeth : ^CHMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_BDINT : STRUCT
    pCh : ^SvrCh_BDINT;
    dData : BDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_DINT : STRUCT
    pMeth : ^CHMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_DINT : STRUCT
    pCh : ^SvrCh_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_HDINT : STRUCT
    pMeth : ^CHMETH;
    dData : HDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_HDINT : STRUCT
    pCh : ^SvrCh_HDINT;
    dData : HDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_RunningStateEnum : STRUCT
    pMeth : ^CHMETH;
    dData : RunningStateEnum;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_RunningStateEnum : STRUCT
    pCh : ^SvrCh_RunningStateEnum;
    dData : RunningStateEnum;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_UDINT : STRUCT
    pMeth : ^CHMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_UDINT : STRUCT
    pCh : ^SvrCh_UDINT;
    dData : UDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd_DINT : STRUCT
    pMeth : ^CMDMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__16Alarms : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_16Alarms;
  END_STRUCT;
  CltChCmd__AlarmX0Para : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_AlarmX0Para;
  END_STRUCT;
  CltChCmd__AlarmX1Para : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_AlarmX1Para;
  END_STRUCT;
  SvrChCmd__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CMDMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__AxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_AxisBase;
  END_STRUCT;
  SvrChCmd_BDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__Bit32 : STRUCT
    pCh : ^SvrChCmd_BDINT;
    dData : BDINT;
    pCmd : ^_Bit32;
  END_STRUCT;
  CltChCmd__Can : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Can;
  END_STRUCT;
  CltChCmd__CheckSum : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_CheckSum;
  END_STRUCT;
  CltChCmd__FileSys : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_FileSys;
  END_STRUCT;
  CltChCmd__Grafix : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Grafix;
  END_STRUCT;
  CltChCmd__IP : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_IP;
  END_STRUCT;
  CltChCmd__Linker : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Linker;
  END_STRUCT;
  CltChCmd__LMCABSEncoder : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCABSEncoder;
  END_STRUCT;
  CltChCmd__LMCAxis : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxis;
  END_STRUCT;
  CltChCmd__LMCAxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxisBase;
  END_STRUCT;
  CltChCmd__LMCAxisRef : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisRef;
  END_STRUCT;
  CltChCmd__LMCAxisVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVis;
  END_STRUCT;
  CltChCmd__LMCAxisVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisInt;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogHandle : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogHandle;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogViewer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogViewer;
  END_STRUCT;
  CltChCmd__LMCAxisVisPara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisPara;
  END_STRUCT;
  CltChCmd__LMCBaseCoord : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCBaseCoord;
  END_STRUCT;
  SvrChCmd_ProfileCommandStatus : STRUCT
    pMeth : ^CMDMETH;
    dData : ProfileCommandStatus;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__LMCCalcModelBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCCalcModelBase;
  END_STRUCT;
  CltChCmd__LMCCalcModelController : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCCalcModelController;
  END_STRUCT;
  CltChCmd__LMCMath_SO3 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCMath_SO3;
  END_STRUCT;
  CltChCmd__LMCMathFunctions : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCMathFunctions;
  END_STRUCT;
  CltChCmd__LMCProfileBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCProfileBase;
  END_STRUCT;
  CltChCmd__LMCProfileBuffer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileBuffer;
  END_STRUCT;
  CltChCmd__LMCProfileLog : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileLog;
  END_STRUCT;
  CltChCmd__LMCProfileVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVis;
  END_STRUCT;
  CltChCmd__LMCProfileVisAxis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisAxis;
  END_STRUCT;
  CltChCmd__LMCProfileVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisInt;
  END_STRUCT;
  CltChCmd__LMCProfileVisMovePara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisMovePara;
  END_STRUCT;
  CltChCmd__LMCPublisher : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCPublisher;
  END_STRUCT;
  CltChCmd__LMCRefBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCRefBase;
  END_STRUCT;
  CltChCmd__LMCRobotLog : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCRobotLog;
  END_STRUCT;
  CltChCmd__LMCSafety : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCSafety;
  END_STRUCT;
  CltChCmd__LMCTool : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCTool;
  END_STRUCT;
  CltChCmd__Lse : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Lse;
  END_STRUCT;
  CltChCmd__MultiTask : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_MultiTask;
  END_STRUCT;
  CltChCmd__OSKernel : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_OSKernel;
  END_STRUCT;
  CltChCmd__OsziLSEBackground : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_OsziLSEBackground;
  END_STRUCT;
  CltChCmd__StdLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_StdLib;
  END_STRUCT;
  CltChCmd__SysMsg : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SysMsg;
  END_STRUCT;
  CltChCmd__TaskObjectControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_TaskObjectControl;
  END_STRUCT;
  CltChCmd_AccessControlMain : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^AccessControlMain;
  END_STRUCT;
  CltChCmd_AlarmDisplayList2 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^AlarmDisplayList2;
  END_STRUCT;
  CltChCmd_AlarmTitleLine : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^AlarmTitleLine;
  END_STRUCT;
  CltChCmd_ASCII_BIN : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ASCII_BIN;
  END_STRUCT;
  CltChCmd_Comm_SendData : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Comm_SendData;
  END_STRUCT;
  CltChCmd_Controller : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Controller;
  END_STRUCT;
  SvrChCmd_UDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_CriticalSection : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^CriticalSection;
  END_STRUCT;
  CltChCmd_DataManager : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DataManager;
  END_STRUCT;
  CltChCmd_DataManagerFIFO : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^DataManagerFIFO;
  END_STRUCT;
  CltChCmd_DataManagerPriority : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^DataManagerPriority;
  END_STRUCT;
  SvrChCmd_DATE_LSL : STRUCT
    pMeth : ^CMDMETH;
    dData : DATE_LSL;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_DateAndTime : STRUCT
    pCh : ^SvrChCmd_DATE_LSL;
    dData : DATE_LSL;
    pCmd : ^DateAndTime;
  END_STRUCT;
  SvrChCmd_iprStates : STRUCT
    pMeth : ^CMDMETH;
    dData : iprStates;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_Diagnostic : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^Diagnostic;
  END_STRUCT;
  CltChCmd_DiagnosticBase : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^DiagnosticBase;
  END_STRUCT;
  CltChCmd_DiagnosticStationFileFolderHandler : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^DiagnosticStationFileFolderHandler;
  END_STRUCT;
  CltChCmd_DiagnosticStationHandlerBase : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^DiagnosticStationHandlerBase;
  END_STRUCT;
  CltChCmd_DiagnosticUserFunction : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^DiagnosticUserFunction;
  END_STRUCT;
  CltChCmd_DiagnosticUserFunction_PLC : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^DiagnosticUserFunction_PLC;
  END_STRUCT;
  CltChCmd_DiagnosticWork : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^DiagnosticWork;
  END_STRUCT;
  CltChCmd_DiagnosticWork_PLC : STRUCT
    pCh : ^SvrChCmd_iprStates;
    dData : iprStates;
    pCmd : ^DiagnosticWork_PLC;
  END_STRUCT;
  CltChCmd_DINT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_DisplaySettings : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DisplaySettings;
  END_STRUCT;
  CltChCmd_EventJournal : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^EventJournal;
  END_STRUCT;
  CltChCmd_EventQueue : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^EventQueue;
  END_STRUCT;
  CltChCmd_FileTransfer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^FileTransfer;
  END_STRUCT;
  CltChCmd_FileTransfer_RecvData : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^FileTransfer_RecvData;
  END_STRUCT;
  SvrChCmd__FT_State_PTofCls_FileTransferHandle : STRUCT
    pMeth : ^CMDMETH;
    dData : FileTransferHandle::_FT_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_FileTransferHandle : STRUCT
    pCh : ^SvrChCmd__FT_State_PTofCls_FileTransferHandle;
    dData : FileTransferHandle::_FT_State;
    pCmd : ^FileTransferHandle;
  END_STRUCT;
  CltChCmd_FolderTransfer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^FolderTransfer;
  END_STRUCT;
  CltChCmd_GetBroadCastData : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GetBroadCastData;
  END_STRUCT;
  CltChCmd_GetOSVer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GetOSVer;
  END_STRUCT;
  CltChCmd_GetTaskHandle : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GetTaskHandle;
  END_STRUCT;
  CltChCmd_GiveConfigNumber : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GiveConfigNumber;
  END_STRUCT;
  CltChCmd_Graphic : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Graphic;
  END_STRUCT;
  CltChCmd_KeyPadAnumFileExplorer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^KeyPadAnumFileExplorer;
  END_STRUCT;
  CltChCmd_KeyPadImages : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^KeyPadImages;
  END_STRUCT;
  CltChCmd_KeyPadImagesStdTemplate : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^KeyPadImagesStdTemplate;
  END_STRUCT;
  CltChCmd_LasalBuiltDate : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^LasalBuiltDate;
  END_STRUCT;
  CltChCmd_Logic_And_10 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Logic_And_10;
  END_STRUCT;
  CltChCmd_LseBuiltDate : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^LseBuiltDate;
  END_STRUCT;
  CltChCmd_Merker : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Merker;
  END_STRUCT;
  CltChCmd_MerkerEx : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^MerkerEx;
  END_STRUCT;
  CltChCmd_NetworkConfig : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^NetworkConfig;
  END_STRUCT;
  CltChCmd_ProfileCommandStatus : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_ProjectGlobal : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ProjectGlobal;
  END_STRUCT;
  CltChCmd_Ram : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Ram;
  END_STRUCT;
  CltChCmd_RAMex : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RAMex;
  END_STRUCT;
  CltChCmd_RamRingBuffer : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RamRingBuffer;
  END_STRUCT;
  CltChCmd_ReceiveDataCMD : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ReceiveDataCMD;
  END_STRUCT;
  CltChCmd_ReceiveDataCMD_PLC : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ReceiveDataCMD_PLC;
  END_STRUCT;
  CltChCmd_RecipeHandle : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^RecipeHandle;
  END_STRUCT;
  CltChCmd_RecipeName : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^RecipeName;
  END_STRUCT;
  CltChCmd_SCL_GetClassVersion : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SCL_GetClassVersion;
  END_STRUCT;
  CltChCmd_SendDataCMD : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SendDataCMD;
  END_STRUCT;
  CltChCmd_SendDataCMD_PLC : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SendDataCMD_PLC;
  END_STRUCT;
  CltChCmd_SigCLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SigCLib;
  END_STRUCT;
  CltChCmd_Standard : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Standard;
  END_STRUCT;
  CltChCmd_String : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^String;
  END_STRUCT;
  CltChCmd_StringBaseGB : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^StringBaseGB;
  END_STRUCT;
  CltChCmd_StringInternal : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringInternal;
  END_STRUCT;
  CltChCmd_StringRAM : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringRAM;
  END_STRUCT;
  CltChCmd_System : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^System;
  END_STRUCT;
  CltChCmd_SystemLogging : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SystemLogging;
  END_STRUCT;
  CltChCmd_TCPCommunication : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TCPCommunication;
  END_STRUCT;
  CltChCmd_TCPCommunicationLogFilter : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TCPCommunicationLogFilter;
  END_STRUCT;
  CltChCmd_TCPComReceiveData : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TCPComReceiveData;
  END_STRUCT;
  CltChCmd_TCPComSendData : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TCPComSendData;
  END_STRUCT;
  CltChCmd_TerminalControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TerminalControl;
  END_STRUCT;
  CltChCmd_TitleLine : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TitleLine;
  END_STRUCT;
  SvrCh__CommandList_PTofCls__LMCAxisBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAxisBase::_CommandList;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__DDE_DATIM : STRUCT
    pMeth : ^CHMETH;
    dData : _DDE_DATIM;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FT_State_PTofCls_FileTransferHandle : STRUCT
    pMeth : ^CHMETH;
    dData : FileTransferHandle::_FT_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FT_SubState_PTofCls_FileTransferHandle : STRUCT
    pMeth : ^CHMETH;
    dData : FileTransferHandle::_FT_SubState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_CMDERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_CMDERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR_CONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR_CONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVE_RELATIVE_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVE_RELATIVE_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEDIRECTION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEDIRECTION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POSMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POSMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POWER_OFF_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POWER_OFF_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_REFMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_REFMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPOSITION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPOSITION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETSWENDPOS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETSWENDPOS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_STATUS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_STATUS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCCONTROLLERTYPE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCCONTROLLERTYPE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROF_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROF_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCIRCLEDEF : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCIRCLEDEF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRORTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRORTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRWARNCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRWARNCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFILESTATES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFILESTATES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFMOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFMOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERAXIS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERAXIS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERGROUPS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERGROUPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFTRANSMODES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFTRANSMODES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__POSFLAGS : STRUCT
    pMeth : ^CHMETH;
    dData : _POSFLAGS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__ROBOT_MODE_PTofCls__LMCRobotBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCRobotBase::_ROBOT_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__ROBOT_STATUS_PTofCls__LMCRobotBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCRobotBase::_ROBOT_STATUS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_DM_CPU_Types : STRUCT
    pMeth : ^CHMETH;
    dData : DM_CPU_Types;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_e_GetOptions_PTofCls_NetworkConfig : STRUCT
    pMeth : ^CHMETH;
    dData : NetworkConfig::e_GetOptions;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_e_SetOptions_PTofCls_NetworkConfig : STRUCT
    pMeth : ^CHMETH;
    dData : NetworkConfig::e_SetOptions;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_EventTypeTxt_PTofCls_SCBase : STRUCT
    pMeth : ^CHMETH;
    dData : SCBase::EventTypeTxt;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_Exec_PTofCls__FileExplorer : STRUCT
    pMeth : ^CHMETH;
    dData : _FileExplorer::Exec;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_FexSortCrit_PTofCls__FileExplorer : STRUCT
    pMeth : ^CHMETH;
    dData : _FileExplorer::FexSortCrit;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_iprStates : STRUCT
    pMeth : ^CHMETH;
    dData : iprStates;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_OptiesEnum : STRUCT
    pMeth : ^CHMETH;
    dData : OptiesEnum;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_T_BITS_PTofCls_EventExport : STRUCT
    pMeth : ^CHMETH;
    dData : EventExport::T_BITS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_T_BITS_PTofCls_EventJournal : STRUCT
    pMeth : ^CHMETH;
    dData : EventJournal::T_BITS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication : STRUCT
    pMeth : ^CHMETH;
    dData : TCPCommunication::t_e_ConnectionType;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_ExportState_PTofCls_TCPCommunicationLogViewer : STRUCT
    pMeth : ^CHMETH;
    dData : TCPCommunicationLogViewer::t_e_ExportState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_TIME_LSL : STRUCT
    pMeth : ^CHMETH;
    dData : TIME_LSL;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd__FSM_TCP_USER : STRUCT
    pMeth : ^CMDMETH;
    dData : _FSM_TCP_USER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_HDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : HDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_IO_State : STRUCT
    pMeth : ^CMDMETH;
    dData : IO_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_T_BITS_PTofCls_Bit32Mask : STRUCT
    pMeth : ^CMDMETH;
    dData : Bit32Mask::T_BITS;
    pDsc : ^SVRDSC;
  END_STRUCT;
END_TYPE
